---
# No auth + full monitoring test.
- name: Test no auth + full monitoring
  hosts: all
  become: true
  roles:
    - role: common
    - role: docker
    - role: secrets
    - role: traefik
    - role: auth
    - role: monitoring
    - role: deploy
