---
all:
  children:
    drayve:
      hosts:
        drayve-test:
          ansible_host: 178.104.36.2
          ansible_user: root
          drayve_domain: drayve-test.woo42.de
          drayve_hostname: drayve-test
